### ISSUE TITLE
Can't compile on Solaris

### ISSUE THREAD

**Issue by jdelStrother** [headius/ruby-atomic#23]
Hi there, I had a bit of trouble compiling ruby-atomic on a Solaris box.   By default, gcc was complaining that __sync_bool_compare_and_swap was undefined.  I had to set march=native (or march=i686) to persuade it to work.

This is with i386-solaris2.10, running gcc 4.4.5 - I'm not sure what the best way of detecting the problem is.  Something like 

``` diff
diff --git a/ext/extconf.rb b/ext/extconf.rb
index 6ea5c08..583dd75 100644
--- a/ext/extconf.rb
+++ b/ext/extconf.rb
@@ -15,7 +15,7 @@ extension_name = 'atomic_reference'
 dir_config(extension_name)

 case CONFIG["arch"]
-when /mswin32|mingw/
+when /mswin32|mingw|solaris/
     $CFLAGS += " -march=native"
 end
```

?

**Comment by headius** [comment]
If this fixes it for you, I'd be fine pulling it in. Will look into that.

**Comment by headius** [comment]
I've also pushed atomic-1.1.10 gems.

**Comment by leews** [comment]
I still can't compile on Solaris 64bit.
I installed ruby 32bit.
gem install atomic

/usr/local/lib/ruby/2.0.0/mkmf.rb:430:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/2.0.0/mkmf.rb:515:in`try_link0'
        from /usr/local/lib/ruby/2.0.0/mkmf.rb:813:in `try_run'
        from extconf.rb:22:in`<main>'

Gem files will remain installed in /usr/local/lib/ruby/gems/2.0.0/gems/atomic-1.1.10 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.0.0/gems/atomic-1.1.10/ext/gem_make.out

**Comment by headius** [comment]
@leews Please open a new issue and we'll see if we can figure out what makefile changes we need to make for you.

**Comment by marksolaris** [comment]
https://github.com/headius/ruby-atomic/issues/29
